// Generated by CoffeeScript 1.6.3
var MainController, trakt;

trakt = angular.module("trakt", []);

MainController = function($scope, $http) {
  angular.extend($scope, {
    apiKey: "53a8e19b109858453b16650b1ede8a7f",
    results: [],
    availableGenres: [],
    filterText: null,
    genreFilter: null,
    orderFields: [
      {
        label: 'Air Date',
        value: "episode.first_aired"
      }, {
        label: 'Rating',
        value: 'episode.ratings.percentage'
      }
    ],
    orderDirections: ["Descending", "Ascending"],
    orderReverse: false
  });
  $scope.selectGenre = function(genre) {
    return $scope.genreFilter = genre;
  };
  return $scope.init = function() {
    var apiDate, today, url;
    today = new Date;
    apiDate = today.getFullYear() + ("0" + (today.getMonth() + 1)).slice(-2) + "" + ("0" + today.getDate()).slice(-2);
    url = 'http://api.trakt.tv/calendar/premieres.json/' + $scope.apiKey + '/' + apiDate + '/' + 30 + '/?callback=JSON_CALLBACK';
    return $http.jsonp(url).success(function(data) {
      $scope.results = data.reduce(function(prev, current, i, arr) {
        return prev.concat(current.episodes.map(function(value) {
          value.date = arr[i].date;
          return value;
        }));
      }, []);
      $scope.availableGenres = $scope.results.reduce(function(prev, current, index, arr) {
        return prev.concat(current.show.genres.filter(function(el) {
          if (prev.indexOf(el) < 0) {
            return el;
          }
        }));
      }, []);
      return console.log($scope.availableGenres);
    }).error(function(error) {});
  };
};

/*
//@ sourceMappingURL=app.map
*/
