// Generated by CoffeeScript 1.6.3
var MainController, trakt;

trakt = angular.module("trakt", []);

MainController = function($scope, $http, $timeout) {
  angular.extend($scope, {
    apiKey: "53a8e19b109858453b16650b1ede8a7f",
    results: [],
    filteredShows: [],
    availableGenres: [],
    filterText: null,
    genreFilter: null,
    networkFilter: null,
    filteredGenres: [],
    orderFields: [
      {
        label: 'Air Date',
        value: "episode.first_aired"
      }, {
        label: 'Rating',
        value: 'episode.ratings.percentage'
      }, {
        label: "Network",
        value: "show.network"
      }
    ],
    orderDirections: ["Descending", "Ascending"],
    orderReverse: false,
    emptyMessage: "Loading TV shows please wait..."
  });
  $scope.$watch("filteredShows.length", function() {
    var res;
    res = $scope.filteredShows.reduce(function(prev, current, i, arr) {
      return prev.concat(current.show.genres.filter((function(genre) {
        return genre.trim().length > 1 && prev.indexOf(genre) < 0;
      })));
    }, []).sort();
    $scope.availableGenres = res;
    if ($scope.availableGenres.indexOf($scope.genreFilter) < 0) {
      return $timeout((function() {
        return $scope.genreFilter = null;
      }), 0);
    }
  }, false);
  $scope.selectNetwork = function(network) {
    return $scope.networkFilter = network;
  };
  $scope.selectGenre = function(genre) {
    return $scope.genreFilter = genre;
  };
  return $scope.init = function() {
    var apiDate, today, url;
    today = new Date;
    apiDate = today.getFullYear() + ("0" + (today.getMonth() + 1)).slice(-2) + "" + ("0" + today.getDate()).slice(-2);
    url = 'http://api.trakt.tv/calendar/premieres.json/' + $scope.apiKey + '/' + apiDate + '/' + 100 + '/?callback=JSON_CALLBACK';
    return $http.jsonp(url).success(function(data) {
      $scope.results = data.reduce(function(prev, current, i, arr) {
        return prev.concat(current.episodes.map(function(value) {
          value.date = arr[i].date;
          return value;
        }));
      }, []);
      console.log($scope.availableGenres);
      console.log($scope.results);
      $scope.networks = $scope.results.reduce(function(prev, current, index, arr) {
        if (current.show.network.trim().length > 1 && prev.indexOf(current.show.network) < 0) {
          prev.push(current.show.network);
        }
        return prev;
      }, []).sort();
    }).error(error(function() {
      return $scope.emptyMessage = "Loading TV shows failed , please refresh the page.";
    }));
  };
};

/*
//@ sourceMappingURL=app.map
*/
